import type { Bean, Recipe } from "./models";

export const blankBean = (): Bean => ({
  id: Date.now(),
  name: "",
  roaster: "",
  brew_style: "hot",
  cups: 1,
  brewer: "xBloom Omni",
  country: "",
  region: "",
  producer: "",
  species: "Arabica",
  variety: "",
  process: "Washed",
  bean_size: "",
  process_detail: "",
  roast_level: "Medium-light",
  tasting_notes: "",
  desired_cup: "",
});

export const initialRecipes: Recipe[] = [
  {
    id: 1,
    name: "Morning Bloom",
    roaster: "Onyx",
    origin: "Ethiopia · Natural",
    temp: 93,
    ratio: "1:16",
    duration: "2:45",
    color: "#d78252",
    grind: 50,
    rpm: 80,
    dose: 18,
    unit: "ml",
    useGrinder: true,
    brewStyle: "hot",
    iceGrams: 0,
    pours: [
      {
        volume: 50,
        temp: 93,
        flow: 3,
        pauseBefore: 5,
        pauseAfter: 30,
        pattern: "spiral",
        agitationBefore: false,
        agitationAfter: false,
      },
      {
        volume: 119,
        temp: 93,
        flow: 3.5,
        pauseBefore: 0,
        pauseAfter: 10,
        pattern: "spiral",
        agitationBefore: false,
        agitationAfter: false,
      },
      {
        volume: 119,
        temp: 93,
        flow: 3.5,
        pauseBefore: 0,
        pauseAfter: 0,
        pattern: "spiral",
        agitationBefore: false,
        agitationAfter: false,
      },
    ],
  },
  {
    id: 2,
    name: "Citrus Study",
    roaster: "April",
    origin: "Kenya · Washed",
    temp: 92,
    ratio: "1:15",
    duration: "3:05",
    color: "#d3a83e",
    grind: 48,
    rpm: 80,
    dose: 18,
    unit: "ml",
    useGrinder: true,
    brewStyle: "hot",
    iceGrams: 0,
    pours: [
      {
        volume: 55,
        temp: 92,
        flow: 3,
        pauseBefore: 5,
        pauseAfter: 35,
        pattern: "circular",
        agitationBefore: false,
        agitationAfter: true,
      },
      {
        volume: 110,
        temp: 92,
        flow: 3.4,
        pauseBefore: 0,
        pauseAfter: 15,
        pattern: "spiral",
        agitationBefore: false,
        agitationAfter: false,
      },
      {
        volume: 105,
        temp: 91,
        flow: 3.5,
        pauseBefore: 0,
        pauseAfter: 0,
        pattern: "spiral",
        agitationBefore: false,
        agitationAfter: false,
      },
    ],
  },
  {
    id: 3,
    name: "Soft Landing",
    roaster: "Sey",
    origin: "Colombia · Honey",
    temp: 90,
    ratio: "1:17",
    duration: "2:55",
    color: "#668b74",
    grind: 55,
    rpm: 70,
    dose: 17,
    unit: "g",
    useGrinder: true,
    brewStyle: "hot",
    iceGrams: 0,
    pours: [
      {
        volume: 50,
        temp: 90,
        flow: 3,
        pauseBefore: 5,
        pauseAfter: 30,
        pattern: "center",
        agitationBefore: true,
        agitationAfter: false,
      },
      {
        volume: 119,
        temp: 90,
        flow: 3.3,
        pauseBefore: 0,
        pauseAfter: 10,
        pattern: "circular",
        agitationBefore: false,
        agitationAfter: false,
      },
      {
        volume: 120,
        temp: 89,
        flow: 3.4,
        pauseBefore: 0,
        pauseAfter: 0,
        pattern: "spiral",
        agitationBefore: false,
        agitationAfter: false,
      },
    ],
  },
];
